### ISSUE TITLE
Kolorowanie kodu dopiero przy pierwszym requescie

### ISSUE THREAD

**Issue by gswirski** [gswirski/morse#6]
Skrypt shellowy dostanie znacznego przyspieszenia.

Może lepiej w ogóle znaleźć bibliotekę, która potrafi kolorować po stronie użytkownika? Odciąży serwer, a odwiedzający dostarczy nam wersję pokolorowaną nic o tym nie wiedząc (+ zwykły cache w bazie, tak jak to było dotychczas). :)

Heilman, masz ochotę?

**Comment by piohei** [comment]
No mogę spróbować. :)
